### ISSUE TITLE
AttributeError: 'list' object has no attribute 'get'

### ISSUE THREAD

**Issue by mawkler** [mireq/luasnip-snippets#3] opened 2024-01-17 10:36 UTC
Hi! Thanks for this absolutely awesome snippet library!

When moving nvim-cmp's selection to a snippet, I get the error "AttributeError: 'list' object has no attribute 'get'". Do you have any idea what could be causing this?

This is the gist of my config ([link to full config](https://github.com/mawkler/nvim/blob/db29a0d05c1b1e43b12bcc773176181df4884c58/lua/configs/luasnip.lua#L17-L28C7)):

```lua
local luasnip = require('luasnip')
local snippets_snip_utils = require('luasnip_snippets.common.snip_utils')

luasnip.config.setup({ history = true })
snippets_snip_utils.setup()

luasnip.setup({
  load_ft_func = snippets_snip_utils.load_ft_func,
  ft_func = snippets_snip_utils.ft_func,
})

require('luasnip.loaders.from_vscode').load({
  paths = { '~/.config/nvim/snippets' },
})
```

**Comment by mireq** [comment] 2024-02-04 16:57
What is exact snippet name?

There are maybe some snippets with buggy code, but i have no testing framework yet and i am currently working on headless transpiler version (without running neovim, it's in develop branch).

**Comment by mawkler** [comment] 2024-02-05 10:21
@mireq One of the snippets is `todo`, which I'm guessing is [this one](https://github.com/mireq/luasnip-snippets/blob/main/lua/luasnip_snippets/all.lua#L424-L426).

**Comment by mireq** [comment] 2024-02-05 15:53
@mawkler it looks like problem in [get_comment_format](https://github.com/mireq/luasnip-snippets/blob/341deea9c9904b4bf16942973dfaf3bf10d68f51/pythonx/vimsnippets.py#L66) function. It's directly copied from UltiSnips (compatibility). I think, this function throws error with specific commentstring or comments variable. Can you check this variables and send it's contents? I suspect, problem can be treesitter.context-commentstring.

**Comment by mawkler** [comment] 2024-02-06 14:34
@mireq How do I get a hold of the printed output from the Python code? I tried wrapping some variables in the function you linked in `print()`, but I don't see any output inside Neovim 🤔

**Comment by mireq** [comment] 2024-02-06 14:41
@mawkler `:messages` command shows standard output (print) and error messages.

**Comment by mawkler** [comment] 2024-02-06 14:48
@mireq That's what I tried, but now I noticed now that I don't get the `print()` output until I actually trigger the snippet. The original error message (`AttributeError: 'list' object has no attribute 'get'`) appears immediately when I hover over the option with nvim-cmp (I'm guessing that it's the snippets preview window that triggers the LuaSnip code). That to me indicates that it's not the function you linked that is the culprint 🤔

Regardless, here's the output (after triggering the `todo` snippet in a Markdown file):

```
AttributeError: 'list' object has no attribute 'get'; :h luasnip-docstring for more info
commentstring = <!--%s-->
comments = [('SINGLE_CHAR', '+', '+', '+', ''), ('SINGLE_CHAR', '-', '-', '-', ''), ('SINGLE_CHAR', '*', '*', '*', '')]
commentstring = <!--%s-->
comments = [('SINGLE_CHAR', '+', '+', '+', ''), ('SINGLE_CHAR', '-', '-', '-', ''), ('SINGLE_CHAR', '*', '*', '*', '')]
commentstring = <!--%s-->
comments = [('SINGLE_CHAR', '+', '+', '+', ''), ('SINGLE_CHAR', '-', '-', '-', ''), ('SINGLE_CHAR', '*', '*', '*', '')]
commentstring = <!--%s-->
comments = [('SINGLE_CHAR', '+', '+', '+', ''), ('SINGLE_CHAR', '-', '-', '-', ''), ('SINGLE_CHAR', '*', '*', '*', '')]
```

Here's how I modified the function:

```python
def get_comment_format():
    commentstring = vim.eval("&commentstring")
    print("commentstring =", commentstring)
    if commentstring.endswith("%s"):
        c = commentstring[:-2]
        print("c =", c)
        return (c.rstrip(), c.rstrip(), c.rstrip(), "")
    comments = _parse_comments(vim.eval("&comments"))
    print("comments =", comments)
    for c in comments:
        if c[0] == "SINGLE_CHAR":
            return c[1:]
    return comments[0][1:]
```

**Comment by mireq** [comment] 2024-02-06 18:22
@mawkler can you try develop branch?

**Comment by mawkler** [comment] 2024-02-10 20:32
@mireq I seem to get the same behaviour on the `develop` branch

**Comment by mireq** [comment] 2024-02-11 08:53
@mawkler this is really strange. I have no idea where is the problem, but i can give you the worst response which you can hear from programmer - it works for me - [video](https://youtu.be/Ah8HnbccIoE) :)

Could you wrap whole execute_code block (`pythonx/luasnip_snippets_python_helper.py`) to try / except block and log errors to something like /tmp/errors.txt?

```python
def execute_code(node_id, node_code, global_code, tabstops, env, indent, match_context, tabstops_idx):
	try:
		global_code = 'import re, os, vim, string, random\n' + '\n'.join(global_code or [])
		codes = (
			global_code,
			node_code,
		)
		compiled_codes = (
			cached_compile(global_code, '<exec-globals>', 'exec'),
			cached_compile(node_code, '<exec-interpolation-code>', 'exec'),
		)

		text = '\n'.join(env.get('LS_SELECT_RAW', []))
		context = None
		start = (int(env['TM_LINE_NUMBER']), int(env['LS_CAPTURE_1']))
		end = (int(env['TM_LINE_NUMBER']), int(env['LS_CAPTURE_2']))
		indent = INDENT_RE.match(env['TM_CURRENT_LINE']).group(0)
		snip = SnippetUtil(indent, vim.eval("visualmode()"), text, context, start, end)
		path = vim.eval('expand("%")') or ""

		source_map = {val: i for i, val in enumerate(tabstops_idx)}

		node_locals = get_node_locals(tuple(node_id))
		node_locals.update({
			't': _Tabs(['\n'.join(tab) for tab in tabstops], source_map),
			'fn': os.path.basename(path),
			'cur': '',
			'res': '',
			'snip': snip,
		})

		if 'regex' in match_context:
			for match in re.finditer(match_context['regex'], match_context['line']):
				if match.end() != len(match_context['line']):
					continue
				else:
					node_locals['match'] = match

		for code, compiled_code in zip(codes, compiled_codes):
			try:
				exec(compiled_code, node_locals)
			except Exception as exception:
				exception.snippet_code = code
				raise

		rv = str(snip.rv if snip._rv_changed else node_locals["res"])
		lines = rv.splitlines()
		return [line[line.startswith(indent) and len(indent):] for line in lines]
	except Exception:
		import traceback
		with open('/tmp/errors.txt', 'a+') as fp:
			fp.write(f'========================\n{traceback.format_exc()}')
```

**Comment by mawkler** [comment] 2024-02-12 17:38
@mireq Here's the logged error:

```python
========================
Traceback (most recent call last):
  File "/home/melker/.local/share/nvim/lazy/luasnip-snippets/pythonx/luasnip_snippets_python_helper.py",
 line 327, in execute_code
    text = '\n'.join(env.get('LS_SELECT_RAW', []))
                     ^^^^^^^
AttributeError: 'list' object has no attribute 'get'
```

**Comment by mireq** [comment] 2024-02-13 05:09
@mawkler this is very strange. Let's dive into details:

Some snippets are built using python. I have ``code_python`` helper function in `common/snip_utils.lua`. This directly forwards `snip.env` to `call_python`. There is no modification and snip.env should be dictionary.

So, bug is either in neovim or in pynvim. Let's check if env is correctly stored to global variable, which is later passed to python bridge:

```lua
local function call_python(python_function_name, opts)
	load_python_helper()
	vim.g.snip_utils_kwargs = opts
	print(vim.inspect(vim.g.snip_utils_kwargs))
	local result = vim.fn.py3eval('luasnip_snippets_python_helper.' .. python_function_name .. '(**(__import__("vim").vars.get("snip_utils_kwargs", {})))')
	vim.g.snip_utils_kwargs = nil
	return result
end
```

On my installation it writes to messages following output:

```
{                                                                                                                                                                                                                                                                                            
  env = {
    LS_CAPTURE_1 = -1,
    LS_CAPTURE_2 = 3,
    LS_SELECT_DEDENT = {},
    LS_SELECT_RAW = {},
    LS_TRIGGER = "todo",
    SELECT_DEDENT = {},
    SELECT_RAW = {},
    TM_CURRENT_LINE = "todo",
    TM_CURRENT_WORD = "todo",
    TM_LINE_INDEX = "0",
    TM_LINE_NUMBER = "1",
    TM_SELECTED_TEXT = {}
  },
  global_code = { 'from vimsnippets import foldmarker, make_box, get_comment_format\nLOREM = """\nLorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod \\\ntempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At \\\nvero eos et accusam et justo 
duo dolores et ea rebum. Stet clita kasd gubergren, \\\nno sea takimata sanctus est Lorem ipsum dolor sit amet.\n"""' },
  indent = "",
  match_context = {},
  node_code = "snip.rv=get_comment_format()[0]",
  node_id = { "all", 31 },
  tabstops = { { "" }, { "TODO" }, { " <13-02-24, yourname>" }, { "13-02-24" }, { ", yourname" } },
  tabstops_idx = { 0, 2, 3, 4, 5 }
}
```

If env is not dictionary, then bug is in neovim. What is exact version of your neovim and pynvim installation?

**Comment by mawkler** [comment] 2024-02-13 07:45
@mireq `env` looks empty for me:

```lua
{
  env = {},
  global_code = { 'from vimsnippets import foldmarker, make_box, get_comment_format\nLOREM = """\nLorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod \\\ntempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At \\\nvero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, \\\nno sea takimata sanctus est Lorem ipsum dolor sit amet.\n"""' },
  indent = "",
  match_context = {},
  node_code = "snip.rv=get_comment_format()[0]",
  node_id = { "all", 31 },
  tabstops = { { "" }, { "TODO" }, { "" }, { "13-02-24" }, { ", yourname" } },
  tabstops_idx = { 0, 2, 3, 4, 5 }
}
```

`nvim --version`:

```sh
NVIM v0.10.0-dev-1962+gc26dc1f77
Build type: RelWithDebInfo
LuaJIT 2.1.1703358377
```

`pynvim` version (`:checkhealth`):

```markdown
Python 3 provider (optional) ~

- `g:python3_host_prog` is not set. Searching for python3 in the environment.
- Executable: /usr/bin/python3
- Python version: 3.11.6
- pynvim version: 0.5.0
- OK Latest pynvim is installed.
```

**Comment by mireq** [comment] 2024-02-14 05:53
@mawkler try it now, it should be fixed.

More context to problem:

Lua -> python bridge can convert object from lua to python automatically with correct type, but only, when it has some keys. If it's empty, there is no way how to distinguish between list and dict. So fix is simple, i have to replace empty variable with empty dictionary.

But i don't really understand, why is env empty.  Without env, [store selection](https://github.com/L3MON4D3/LuaSnip/blob/2dbef19461198630b3d7c39f414d09fb07d1fdd2/doc/luasnip.txt#L3389) will not work.

**Comment by mawkler** [comment] 2024-02-16 17:43
@mireq Thank you, your fix seems to work!

I only get the output `env = {}` when the snippet is displayed in nvim-cmp's preview window. When I trigger `expand`, `env` gets properly populated.

Here's a minimal config to reproduce:

<details>
<summary><b>Click to expand</b></summary>

```lua
local lazypath = vim.fn.stdpath('data') .. '/lazy/lazy.nvim'
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    'git',
    'clone',
    '--filter=blob:none',
    'https://github.com/folke/lazy.nvim.git',
    '--branch=stable', -- latest stable release
    lazypath,
  })
end
vim.opt.rtp:prepend(lazypath)

require('lazy').setup({
  {
    'mireq/luasnip-snippets',
    dependencies = { 'L3MON4D3/LuaSnip', 'hrsh7th/nvim-cmp' },
    config = function()
      require('luasnip_snippets.common.snip_utils').setup()
    end,

  },
  {
    'L3MON4D3/LuaSnip',
    dependencies = 'nvim-treesitter/nvim-treesitter',
    config = true,
  },
  {
    'hrsh7th/nvim-cmp',
    dependencies = { 'saadparwaiz1/cmp_luasnip' },
    config = function()
      local cmp = require 'cmp'

      cmp.setup({
        completion = { completeopt = 'menu,menuone,noinsert' },
        mapping = cmp.mapping.preset.insert {
          ['<C-j>'] = cmp.mapping.select_next_item(),
          ['<C-k>'] = cmp.mapping.select_prev_item(),
          ['<Tab>'] = cmp.mapping(function() require('luasnip').expand() end, { 'i', 's' }) },
        sources = {
          { name = 'luasnip' },
        },
      })
    end,
  },
})
```

</details>

1. `> nvim -u path/to/file/above foo.md`
2. Enter insert mode
3. Type `todo`, then `<Esc>`
4. Check `:messages`

**Comment by mireq** [comment] 2024-02-17 13:39
@mawkler  Thanks for assistance.

Now i can reproduce problem with older versions. New seems to be Ok. I am closing issue.

**Closed by mireq** 2024-02-17 13:39 UTC

**Comment by mawkler** [comment] 2024-02-19 07:29
@mireq Thank you!
